name             'whenever'
maintainer       'FreeRunning Technologies'
maintainer_email 'contact@freerunningtech.com'
license          'All rights reserved'
description      'Configures whenever'
long_description 'WHENEVER'
version          '0.1.0'
