###
# This is the place to override the gunicorn cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "gunicorn/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Gunicorn timout:
#
#normal[:gunicorn][:timeout] = 30
#normal[:gunicorn][:worker_processes] = 8
